cache:
  directories:
    - "node_modules"
language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: npm
  email: ari@chivuku.la
  api_key: $API_KEY
  skip_cleanup: true
  tag: next
  on:
    branch: master
