language: node_js
node_js:
- node
jobs:
  include:
  - stage: Test
    if: type = push
    script:
    - npm outdated
    - npm run lint
    - npm run test
    - npm run build
  - stage: Deploy
    if: tag IS present
    script:
    - npm run build
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-UNSTABLE$" ]] ; then export NPM_TAG="next" ; fi
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-STABLE$" ]] ; then export NPM_TAG="latest" ; fi
    deploy:
      - provider: npm
        email: $EMAIL
        api_key: $API_KEY
        skip_cleanup: true
        tag: $NPM_TAG
  - stage: Actualize
    if: type = api
    script:
    - npm run snap
    - npm run codegen
    - git remote add target https://arichiv:$GITHUB_TOKEN@github.com/AriChivukula/typescriptase.git
    - git add -A
    - git commit -m "ACTUALIZE $TRAVIS_BUILD_NUMBER"
    - git push target HEAD:$TRAVIS_BRANCH
