language: node_js
node_js:
- node
jobs:
  include:
  - stage: Test
    script:
    - npm outdated
    - npm run lint
    - npm run test
    - npm run build
    deploy:
      - provider: npm
        email: $EMAIL
        api_key: $API_KEY
        skip_cleanup: true
        tag: next
        on:
          tags: true
          condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-UNSTABLE$"
      - provider: npm
        email: $EMAIL
        api_key: $API_KEY
        skip_cleanup: true
        tag: latest
        on:
          tags: true
          condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-STABLE$"
