language: node_js
node_js:
- node
before_install: npm install --global --upgrade yarn
cache: yarn
jobs:
  include:
  - stage: Test
    if: type = push
    install: yarn
    script:
    - yarn outdated
    - yarn ts-node src/cli.ts --expectNoChanges --files gen/*.ts
    - yarn tsc
  - stage: Deploy
    if: tag IS present
    script:
    - yarn tsc
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-UNSTABLE$" ]] ; then export NPM_TAG="next" ; fi
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-STABLE$" ]] ; then export NPM_TAG="latest" ; fi
    install: yarn
    deploy:
      - provider: npm
        email: $EMAIL
        api_key: $API_KEY
        skip_cleanup: true
        tag: $NPM_TAG
        on:
          tags: true
  - stage: Actualize
    if: type = api
    install: yarn
    script:
    - yarn ts-node src/cli.ts --files gen/*.ts
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
