language: node_js
node_js:
- node
before_install: npm install --global --upgrade yarn
cache: yarn
jobs:
  include:
  - stage: Test
    if: ( type = pull_request) OR ( ( branch = master ) AND ( type = push ) )
    install: yarn
    script:
    - yarn outdated
    - yarn test
    - yarn build
  - stage: Deploy
    if: tag IS present
    script:
    - npm run build
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-UNSTABLE$" ]] ; then export NPM_TAG="next" ; fi
    - if [[ "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-STABLE$" ]] ; then export NPM_TAG="latest" ; fi
    install: npm install
    deploy:
      - provider: npm
        email: $EMAIL
        api_key: $API_KEY
        skip_cleanup: true
        tag: $NPM_TAG
        on:
          tags: true
  - stage: Actualize
    if: type = api
    install: yarn
    script:
    - yarn snap
    - yarn codegen
    - git remote add target "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    - git add -A
    - git commit -m "ACTUALIZE ${TRAVIS_BUILD_NUMBER}"
    - git push target HEAD:$TRAVIS_BRANCH
