cache:
  directories:
  - node_modules
language: node_js
node_js:
- node
script:
- npm run lint
- npm run test
- npm run build
deploy:
  - provider: npm
    email: ari@chivuku.la
    api_key: $API_KEY
    skip_cleanup: true
    tag: next
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-UNSTABLE$"
  - provider: npm
    email: ari@chivuku.la
    api_key: $API_KEY
    skip_cleanup: true
    tag: latest
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+-STABLE$"
